name: Tests

on: [push, pull_request]

jobs:
  test:
    name: "Unit Tests"
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true

      - name: Install fastFMM
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: fastFMM

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.x"
          python-version: ${{ matrix.python-version }}

      - name: Test with python ${{ matrix.python-version }}
        run: uv run --extra dev --frozen pytest
