name: Tests

on: [push, pull_request]

jobs:
  test:
    name: "Unit Tests"
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [macos-latest, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true

      - name: Install fastFMM
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: fastFMM

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.x"
          python-version: ${{ matrix.python-version }}
        env:
          LIBRARY_PATH: "$LIBRARY_PATH:/opt/homebrew/lib"
          INCLUDE_PATH: "$INCLUDE_PATH:/opt/homebrew/include"

      - name: Test with python ${{ matrix.python-version }}
        run: uv run --extra dev --frozen pytest
