name: Tests

on: [push, pull_request]

jobs:
  test:
    name: "Unit Tests"
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install fastFMM
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: fastFMM

      - name: Install system requirements
        run: |
          brew install xz pcre2 bzip2 libdeflate  # install R sys dependencies
          brew install libgit2 imagemagick@6  # install bioconductor sys dependencies

      - name: macOS library fix for R 4.4.3
        run: |
          curl -LO https://mac.r-project.org/bin/darwin20/arm64/libdeflate-1.23-darwin.20-arm64.tar.xz
          tar xJf libdeflate-1.23-darwin.20-arm64.tar.xz -C /

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.x"
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          uv sync --extra dev --frozen
        env:
          DYLD_FALLBACK_LIBRARY_PATH: "/opt/homebrew/lib"

      - name: Test with python ${{ matrix.python-version }}
        run: |
          uv run pytest
