name: Publish to PyPI

on:
  push:
    branches:
      - 'publish-to-pypi'
    # paths:
    #   - '.github/workflows/test_publish.yaml'

jobs:
  pypi:
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.x"

      # R must be installed to test installation
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Build package
        run: uv build

      - name: Test installation (wheel)
        run: uv run --isolated --no-project --python 3.13 --with dist/*.whl python -c "from fast_fmm_rpy2.ingest import read_csv_in_pandas_pass_to_r; print('Success!')"

      - name: Test installation (source distribution)
        run: uv run --isolated --no-project --python 3.13 --with dist/*.tar.gz python -c "from fast_fmm_rpy2.ingest import read_csv_in_pandas_pass_to_r; print('Success!')"
